### PR TITLE
Simplify adjacency map conversions using Coercible

### PR DESCRIPTION
**Pull request by snowleopard**

### CODE REVIEW

**Comment by snowleopard** [comment]
@bolt12 You may be interested to have a look how `coerce` can help us get rid of many calls to conversion functions like `fromSymmetric`.

**Comment by bolt12** [comment]
I'm going to have a look!

**Comment by bolt12** [comment]
@snowleopard It appears that the coerce calls on the symmetric is already done, right? I'm sorry that took this long for me to come up to this issue.

**Comment by snowleopard** [comment]
@bolt12 Yes, I already did this, as soon as I realised we can use `coerce` here.

**Pull request merged**
