### PR TITLE
Extend ToGraph

### PR DESCRIPTION
**Pull request by snowleopard**
This is work in progress in preparation for #105.

### CODE REVIEW

**Comment by snowleopard** [comment]
@nobrakal Note that this PR adds an implementation of `reachable`, which I think is part of your graph benchmark suite.

**Comment by nobrakal** [comment]
@snowleopard That is cool to have it included properly in the API! It is the definition I used, so no changes in the results.

**Comment by snowleopard** [comment]
@nobrakal For some reason I get much better speed up of `edgeCount` in non-empty graphs:

`edgeCount: 0.34 (good)`

I have a feeling that the `edgeCount/Int` rule does not fire in `Algebra.Graph`. Do you have any idea why this happens and how to fix it?

**Comment by nobrakal** [comment]
@snowleopard 

The rule actually fired:

> Rule fired: Rule fired: edgeCount/Int (Algebra.Graph)

It will dig in the produced core, it is a really interesting speedup :)

**Comment by snowleopard** [comment]
@nobrakal Thank you! :) 

Also, it looks like `edgeSet` is not part of the testsuite -- I'll try to send you a PR with it soon.

**Comment by snowleopard** [comment]
Thanks, interesting! But why was `edgeCount` slower for non-empty graphs? That's quite strange.

Anyway, I hope to merge this PR later today.

**Comment by fosskers** [comment]
:)

**Comment by snowleopard** [comment]
@fosskers Hope to release this soon :)

**Pull request merged**
