### PR TITLE
Try out make-travis-yml OSX job generation

### PR DESCRIPTION
**Pull request by phadej**
See https://github.com/hvr/multi-ghc-travis/pull/106

### CODE REVIEW

**Comment by snowleopard** [comment]
@phadej Thanks! But I don't see any OSX jobs at the moment:

https://travis-ci.org/snowleopard/alga/builds/314061552?utm_source=github_status&utm_medium=notification

Note that we already have one OSX job:

https://travis-ci.org/snowleopard/alga/builds/312685208

Are you planning to add OSX jobs for all supported GHC versions?

**Comment by phadej** [comment]
My bad. Amended.

**Comment by snowleopard** [comment]
Merged, thank you!

**Comment by phadej** [comment]
@snowleopard one can add jobs for 7.10.3 -- 8.0.2 (older GHC-7.8.4 starts to be problematic on OSX). I don't really see a huge benefit in that.

**Comment by snowleopard** [comment]
@phadej Yes, I think it's enough to have just one OSX job for the latest GHC version for now.

**Pull request merged**
