### PR TITLE
Update CI, add 8.8.1 to the testsuite

### PR DESCRIPTION
**Pull request by snowleopard**

### CODE REVIEW

**Comment by snowleopard** [comment]
@nobrakal Hi there! Could you please do your regular magic with the performance suite? :-)

Happy New Year!

**Comment by snowleopard** [comment]
@nobrakal Never mind, looks like I've figured it out this time :)

**Comment by nobrakal** [comment]
Great @snowleopard  Happy New Year :D

**Comment by snowleopard** [comment]
@nobrakal Strangely, I consistently see poor results for `hasEdge` and `hasVertex` even though there are no changes to the sources:

```
hasEdge: 1.17 (bad)
hasVertex: 1.11 (bad)
```

At first, I thought this was a glitch, but it consistently showed up in 5-6 test runs. 

Any thoughts about why this might happen?

**Comment by nobrakal** [comment]
This is strange, I have absolutely no idea why, I will try to investigate !

**Pull request merged**
