### PR TITLE
Revision in preparation for 0.5

### PR DESCRIPTION
**Pull request by snowleopard**
Doing a revision pass while preparing for a release.

### CODE REVIEW

**Comment by snowleopard** [comment]
@bolt12 @vasalf I've made quite a lot of revisions to undirected and bipartite graphs. Hope I didn't mess up anything important. If you spot anything, please let me know!

**Comment by snowleopard** [comment]
@vasalf I've just realised that I've probably created a lot of rebasing work for you -- sorry about that!

**Comment by bolt12** [comment]
@snowleopard I have looked through the undirected graphs part and it seemed very nice to me! Was there any specific reason to use Symmetric Relation instead of Adjacency Graph? :)

**Comment by snowleopard** [comment]
@bolt12 Thanks! 

> Was there any specific reason to use Symmetric Relation instead of Adjacency Graph?

I'm not entirely sure what you mean. The implementation was already using `Symmetric.Relation`. I just removed some rewrite rules that were supposed to be useful only in future when we switch to `Undirected.AdjacencyMap` as underlying representation (which we don't have yet). I think that at some point we'll just remove all our `Relation` data structures and replace them with corresponding adjacency maps to avoid keeping too many representations in the library :)

**Comment by bolt12** [comment]
Oops right! I don't know why but I had the idea that `AdjacencyMap` was already used, sorry about that!

Overall, from the `Undirected` point of view, I think everything is set! :tada:

**Pull request merged**
