### PR TITLE
Bump LTS to latest and add upper bounds for dependencies

### PR DESCRIPTION
**Pull request by adelbertc**

### CODE REVIEW

**Comment by snowleopard** [comment]
Thanks @adelbertc!

At some point I might reconsider the bounds on package dependencies, but this should be fine for now.

**Comment by ndmitchell** [comment]
I would caution against too many upper bounds - you end up doing a lot of busy work with package version tweaks. However, opinions vary...

**Comment by snowleopard** [comment]
@ndmitchell I haven't yet experienced this myself, but I did manage to find your Shake commit removing all upper bounds, so it seems that you got fed up with them at some point :-)

**Comment by adelbertc** [comment]
Out of curiosity what is the rule of thumb for controlling these bounds? Or is it a case, as you said, that opinions vary?

**Comment by ndmitchell** [comment]
http://neilmitchell.blogspot.co.uk/2014/11/upper-bounds-or-not.html is my explanation.

**Comment by snowleopard** [comment]
Thanks @ndmitchell!

In the case of Alga, we currently only depend on core GHC libraries `array`, `base` and `containers`, which do not change very often and when they do, it's not a surprise. So, omitting upper bounds will most probably minimise the number of times we need to edit the `.cabal` file.

**Comment by adelbertc** [comment]
Gotcha, makes sense - thank you for the explanation!

I'm just getting back into Haskell after a... 4 year hiatus so please excuse my newbie questions :-)

**Pull request merged**
