### PR TITLE
Optimise hasEdge, drop hasSelfLoop

### PR DESCRIPTION
**Pull request by snowleopard**
Work in progress

### CODE REVIEW

**Comment by snowleopard** [comment]
@nobrakal Here is my low-level optimisation :) Need to add some comments!

Let's see what the regression suite says...

**Comment by nobrakal** [comment]
> hasEdge: 0.17 (good)

That is a pretty cool improvement :D

**Comment by snowleopard** [comment]
> hasEdge: 0.17 (good)

🎉

**Comment by snowleopard** [comment]
@nobrakal Looks like we were watching in sync :D

**Comment by snowleopard** [comment]
@nobrakal I now think it wasn't necessary to add `hasSelfLoop`: we can always take care of this special case in `hasEdge` itself. This makes the API smaller, and removes a potential source of confusion from users.

So, I think I'll remove `hasSelfLoop` as part of this PR. What do you think?

**Comment by snowleopard** [comment]
Hmm, my "further simplification" reduced the speed up to just `hasEdge: 0.36 (good)`...

**Comment by snowleopard** [comment]
OK, although the achieved speed up is not as great as initially hoped, I'm merging this. I'm not entirely happy about code duplication and the fact that default implementation in `ToGraph` may be slower than before -- I'd like to come back to this at some point.

**Pull request merged**
