### PR TITLE
Symmetric relation fixes

### PR DESCRIPTION
**Pull request by snowleopard**
A minor revision after #174.

### CODE REVIEW

**Comment by snowleopard** [comment]
@bolt12 Just to let you know: I've done some further work on symmetric relations -- you might be interested to have a look!

**Comment by bolt12** [comment]
Alright! Very interesting changes, why do you said that about the `ToGraph` instance I didn't understand what you mean.

**Comment by snowleopard** [comment]
> why do you said that about the `ToGraph` instance I didn't understand what you mean.

@bolt12 This `ToGraph` instance seems to be incompatible with others because of the way we treat symmetric edges. In particular, [we expect](http://hackage.haskell.org/package/algebraic-graphs-0.3/docs/Algebra-Graph-ToGraph.html#v:edgeSet) that the following property holds:

```haskell
edgeSet == Algebra.Graph.AdjacencyMap.edgeSet . toAdjacencyMap
```

But it doesn't (and we don't test it in the testsuite).

In fact, maybe we need a separate type class `Algebra.Graph.ToGraph.Undirected` or something similar for working with undirected graphs, since they are quite different from directed graphs in terms of the typical operations we apply to them.

**Comment by bolt12** [comment]
Ohh I didn't had that in mind when I wrote that instance.. my bad for not
understanding that it had to obey that property.. If I have time I'll think
of an option for this particular case and add it to the next contribution!

**Comment by snowleopard** [comment]
No problem! Maybe it's worth looking around for other existing APIs for working with undirected graphs.

**Comment by bolt12** [comment]
I will! Probably will fit nicely with the idea of adding support for more
functions like `isConnected`, `nodeDegree`, etc..

**Pull request merged**
