### PR TITLE
Basic Acyclic AdjacencyIntMap

### PR DESCRIPTION
**Pull request by adithyaov**
The idea is that there should be no edge from a higher valued vertex to a lower valued vertex. This is the basic edge rule. If the rule breaks there will be a compilation error.
This is the most basic implementation and is open to constructive debate.

### CODE REVIEW

**Comment by snowleopard** [comment]
Thanks! Here is some feedback:

I think it may be more productive to follow the approach from `NonEmpty.AdjacencyMap` where we simply wrap an existing implementation of adjacency maps into a `newtype`:

https://github.com/snowleopard/alga/blob/master/src/Algebra/Graph/NonEmpty/AdjacencyMap/Internal.hs#L112-L121

This approach allows to reuse a lot of code via type-safe coercions, for example:

https://github.com/snowleopard/alga/blob/master/src/Algebra/Graph/NonEmpty/AdjacencyMap.hs#L200

We also modify the consistency invariant to make sure the graph is non-empty:

https://github.com/snowleopard/alga/blob/master/src/Algebra/Graph/NonEmpty/AdjacencyMap/Internal.hs#L165-L166

In your case you'll use `isAcyclic` instead of `not . isEmpty`.

Also, I don't think we'll be using low-level interfaces like `addEdge` for creating such graphs. I'd prefer to start by adding something like `scc` which is guaranteed to return an acyclic graph. 

Finally, let's first start with a parametric version `AdjacencyMap`, not with an `Int` variant which is just a performance optimisation.

**Comment by snowleopard** [comment]
On a second thought, we might use your type-safe `Edge` idea when implementing a graph construction primitive like `edges`, so let's keep it!

**Comment by adithyaov** [comment]
> I think it may be more productive to follow the approach from NonEmpty.AdjacencyMap where we simply wrap an existing implementation of adjacency maps into a `newtype`.

Agreed! I'll change the implementation.

> Also, I don't think we'll be using low-level interfaces like `addEdge`.

Agreed, I wanted to take feedback on the idea before proceeding further. I believe I can make safe `connect` and `overlay` as well.

> Finally, let's first start with a parametric version AdjacencyMap, not with an Int variant which is just a performance optimization.

I've used the Int variant because it is easier to type check (using the Nat data kind and type level comparision) and convert it from type level to Integer datatype (KnownNat).

Is it possible to promote **any** data type and somehow derieve a type level comparision function for it? 

Parametrization could be possible if we define the AdjacencyMap like such: 
```
newtype AdjacencyIntMap [some phantom types for acyclic checks] a = ...
```
The above design looks more like vertex labeled Graphs.

Is it OK if i keep opening PRs for feedback? Or should I opt for Draft PRs?

**Comment by snowleopard** [comment]
> I've used the Int variant because it is easier to type check (using the Nat data kind and type level comparison) and convert it from type level to Integer datatype (KnownNat).

Note that it's perfectly fine if some functions can only produce `AdjacencyMap Int` as a result. For example, `edges` defined on top of your `Edge` idea could return `AdjacencyMap Int`, but `scc` could return `AdjacencyMap a`.

> Is it possible to promote any data type and somehow derive a type level comparison function for it?

Good question! I don't know the answer. It would be interesting to see if there is a way to promote `Ord` to the type level.

Regarding phantom types: I suggest we look at this option a bit later. It's definitely possible to use phantom types to get rid of a lot of very similar graph types (non-empty, labelled, acyclic, etc.) but it's a separate issue which I suggest to consider at the end of the project.

**Comment by adithyaov** [comment]
> Note that it's perfectly fine if some functions can only produce AdjacencyMap Int as a result. For example, edges defined on top of your Edge idea could return AdjacencyMap Int, but scc could return AdjacencyMap a.

Could you explain how this can be possible with the implementation in this PR? I don't this is possible from the kind of implementation that I provide in the pull request. I'll probably have to change it.

> Regarding phantom types: I suggest we look at this option a bit later.

In this implementation, I am using phantom types though. I believe any kind of type-level programming uses phantom types in some way?

@anfelor has actually suggested that an Acyclic graph could look like the following, ([https://gist.github.com/adithyaov/f87b5b496fd88ef91cfe438dfaf3a955](https://gist.github.com/adithyaov/f87b5b496fd88ef91cfe438dfaf3a955))
```
data Acyclic n a = Acyclic (AdjacencyMap a) (Vector n a)
append :: a -> [Ordinal n] -> Acyclic n a -> Acyclic (S n) a
```
One could probably take this further, I'll experiment with this and get back to you!

**Comment by snowleopard** [comment]
> In this implementation, I am using phantom types though.

Ah, indeed, I didn't notice the phantom parameter at first. 

In this case let's start with a version that only uses `scc` and is just a newtype wrapper around the existing `AdjacencyMap a` data type.

> Could you explain how this can be possible with the implementation in this PR? 

Couldn't you just use `<=?` as a constraint, e.g. something like this?

```haskell
addEdge ::
     forall f t. (KnownNat f, KnownNat t, (f <=? t) ~ True)
  => Edge f t
  -> AdjacencyMap a
  -> AdjacencyMap a
```

**Comment by adithyaov** [comment]
> Couldn't you just use <=? as a constraint, e.g. something like this?

Ah, Interesting!
```
addEdge ::
     forall f t. (KnownNat f, KnownNat t, (f <=? t) ~ True)
  => Edge f t
  -> AdjacencyMap a
  -> AdjacencyMap a
```
In the above, how can one encode a generic type `a` to a natural number? `Edge f t` does not have a meaning if `f` and `t` dont correspond to some vertices. One can restrict the generic type `a` to have an instance of `Integral` (to use `toInteger`). This just does not feel correct.

I think it would be better to use sized Vector and Ordinals for defining an Acyclic Adjacency map.

**Comment by snowleopard** [comment]
Oh, sorry, I meant:

```haskell
addEdge ::
     forall f t. (KnownNat f, KnownNat t, (f <=? t) ~ True)
  => Edge f t
  -> AdjacencyMap Int
  -> AdjacencyMap Int
```

**Comment by snowleopard** [comment]
@adithyaov Are you planning on reviving this PR? If not, please close it. 

In principle, I'd love to see something like `edge` or `edges` for creating acyclic graphs using ordered edges.

**Comment by adithyaov** [comment]
> In principle, I'd love to see something like edge or edges for creating acyclic graphs using ordered edges.

@snowleopard I'll experiment a bit and get back to you.

**Pull request closed without merging**
