### PR TITLE
Give Graph Bifunctor on GHC 7.8 too

### PR DESCRIPTION
**Pull request by gwils**
Replace CPP with a conditional `bifunctors` dependency

### CODE REVIEW

**Comment by snowleopard** [comment]
@gwils This looks good, thanks you! I was actually wondering if I need to continue to support GHC 7.8, but your PR means you still care about it...

**Comment by gwils** [comment]
I don't use 7.8, but I find it difficult to work with APIs which are conditional on GHC version like this. This PR was a very easy change for me to make that could save some theoretical 7.8 user from that pain :)

I would be equally as happy with you dropping 7.8 support instead of merging this PR.

**Comment by snowleopard** [comment]
I see, I'll keep this in mind. Merged now!

**Comment by dalaing** [comment]
Would there be interest in a `Bifoldable` instance as well?

**Comment by snowleopard** [comment]
@dalaing No, because Foldable instances are in general problematic, see the top comment here: https://hackage.haskell.org/package/algebraic-graphs-0.3/docs/Algebra-Graph-ToGraph.html

**Comment by dalaing** [comment]
Ah, yeah - fair enough :)

**Pull request merged**
