### PR TITLE
Recover previous Todo example

### PR DESCRIPTION
**Pull request by chenzizhao**
Per suggestions in #51:
- Resolve namespace conflict between 'AdjacencyGraph' and 'Class'
- Ignore cycles after topSort in `todo`

### CODE REVIEW

**Comment by snowleopard** [comment]
@chenzizhao Many thanks for doing this! Could you please also add the [demo from the blog post](https://blogs.ncl.ac.uk/andreymokhov/graphs-in-disguise/) as a test suite for this module? Otherwise, it's difficult to be sure that it still works as expected. I suggest adding a new test module like `test/Algebra/Graph/Test/Example/Todo.hs` and then calling it from `test/Main.hs`.

**Comment by snowleopard** [comment]
Ignore CI failures for now. I think I need to fix something.

**Comment by chenzizhao** [comment]
@snowleopard I added the examples from the blog (in a rather literal and verbose way). Please let me know if you see any improvements that can be made!

**Comment by snowleopard** [comment]
@chenzizhao Awesome, thank you! I've also fixed the CI problems, so this time it will hopefully succeed.

**Comment by snowleopard** [comment]
Ah, CI still fails -- you need to rebase to master for my changes to kick in.

**Comment by chenzizhao** [comment]
Oops just rebased and let's see how it goes.

**Comment by snowleopard** [comment]
Thanks! CI now reports a problem:
```
neil: The following files have \r characters, trailing whitespace or excess newlines.
/tmp/extra-dir-9843703844600/algebraic-graphs-0.6/test/Algebra/Graph/Test/Example/Todo.hs
```

**Comment by chenzizhao** [comment]
> Thanks! CI now reports a problem:
> 
> ```
> neil: The following files have \r characters, trailing whitespace or excess newlines.
> /tmp/extra-dir-9843703844600/algebraic-graphs-0.6/test/Algebra/Graph/Test/Example/Todo.hs
> ```

**Comment by snowleopard** [comment]
@chenzizhao Merged! Thank you again for doing this :)

**Pull request merged**
