### PR TITLE
Add support for GHC 9.4

### PR DESCRIPTION
**Pull request by snowleopard**
Waiting until 9.4 becomes available.

### CODE REVIEW

**Comment by ocramz** [comment]
9.4.1 is out (https://www.haskell.org/ghc/blog/20220807-ghc-9.4.1-released.html), these CI jobs can be restarted

**Comment by snowleopard** [comment]
We might need to wait a bit more. After restarting, I'm getting:
```
Error: All install methods for ghc 9.4 failed
```

**Comment by snowleopard** [comment]
Retried today with the same results.

**Comment by ysangkok** [comment]
The results are no longer available, would be nice to post them here for posterity.

**Comment by snowleopard** [comment]
> The results are no longer available, would be nice to post them here for posterity.

There was nothing interesting, just some problems with the CI.

I plan to add support for GHC 9.4 (and maybe GHC 9.6) in the next couple of weeks. Stay tuned!

**Pull request closed without merging**
