### PR TITLE
Modified isSubGraph in Labelled.AdjacencyMap, minor error rectified

### PR DESCRIPTION
**Pull request by adithyaov**
Changed `Labelled.AdjacencyMap.isSubGraph`

Please note that I am unable to run the tests (QuickCheck) on my system due to a problem with WSL. So the only option for me to verify if the tests are passing is Travis CI.

### CODE REVIEW

**Comment by snowleopard** [comment]
@adithyaov The following properties should be satisfied by `isSubgraphOf`:

```haskell
isSubgraphOf x (overlay   x y) == True
isSubgraphOf x (connect e x y) == True
isSubgraphOf y (connect e x y) == True
```
I don't think your current implementation satisfies these requirements.

**Comment by snowleopard** [comment]
Also, if you are fixing a bug, please add a test that currently fails but passes with yours fix.

**Comment by adithyaov** [comment]
@snowleopard 
```
isSubgraphOf x (overlay   x y) == True
isSubgraphOf x (connect e x y) == True
isSubgraphOf y (connect e x y) == True
```
Satisfying the properties above becomes really complex. Please note the following, say,
```
x = edge (Sum 2) 0 1
y = edge (Sum -2) 0 1
z = overlay x y = vertices [0, 1]
```
Justifying that `x` is a subgraph of `z` is quite dufficult. We would probably need to check different conditions depending on the Monoid (edge).
In case of `Sum`, `isSubgraphOf  x y = isSubMapOfBy (isSubMapOfBy (\_ _ -> True)) x y` as `Sum` can result in anything.
In case of `Capacity`, `isSubgraphOf  x y = isSubMapOfBy (isSubMapOfBy (\p q -> q <= p)) x y` as `Capacity` can only decrease.
In case of `Distance`, `isSubgraphOf  x y = isSubMapOfBy (isSubMapOfBy (\p q -> q >= p)) x y` as `Distance` can only increase.
I'll get back to this PR after some amount of thought.

**Comment by snowleopard** [comment]
@adithyaov We typically want edge labels to come from a *dioid*:

http://hackage.haskell.org/package/algebraic-graphs-0.4/docs/Algebra-Graph-Label.html#t:Dioid

`Sum` is not a dioid, which is why you have issues here. Combining algebraic graphs and non-dioids is problematic, because many basic properties no longer hold, e.g. `x + x = x`.

Both `Distance` and `Capacity` are dioids, so there should be no issues with them.

**Comment by adithyaov** [comment]
@snowleopard 
Ah, I see, In that case, I believe the previous example is correct. I think one should probably change `isSubgraphOf` to work only with dioids.

**Comment by snowleopard** [comment]
> I think I got an error as I was checking it for a Sum Monoid.

Right, I see. Indeed, with `Sum` there will be a few issues. I added a note about this: https://github.com/snowleopard/alga/issues/175#issuecomment-513222730.

If the current implementation works for dioids, then I think there is no need to change anything for now, but we'll definitely need to improve documentation for edge-lebelled graphs, as discussed in #175.

**Comment by adithyaov** [comment]
#175 Closing this PR for now. Please feel free to reopen this if required.

**Pull request closed without merging**
